[package]
name = "home-os-kernel"
version = "0.1.0"
description = "home-os kernel - A modern, minimal operating system"
authors = ["home-os contributors"]

[dependencies]
# Reference local Home packages
multiboot2 = { path = "../../home/packages/kernel" }
ffi = { path = "../../home/packages/ffi" }
threading = { path = "../../home/packages/threading" }
basics = { path = "../../home/packages/basics" }

[build]
target = "x86_64-freestanding-none"
optimize = "ReleaseSafe"
code_model = "kernel"
linker_script = "linker.ld"

[build.assembly]
# Boot assembly file
boot = "src/boot.s"
