#!/usr/bin/env python3
"""Build and sign a home-os package.

The format is deliberately flat and explicit, because the reader is a kernel
with no allocator to spare and every field it trusts has to be bounded before
it is used:

    magic       8 bytes  "HPKG0001"
    file_count  u32      little-endian
    payload_len u32      bytes of the entries section
    entries     payload_len bytes
                  per entry: u32 name_len, name, u32 data_len, data
                  each of name and data padded to a 4-byte boundary
    sig_len     u32
    signature   sig_len bytes, RSA PKCS#1 v1.5 over SHA-256 of
                everything before sig_len

The signature covers the header as well as the entries, so a package cannot be
made to describe a different number of files than it carries.

Usage:
  make-package.py --genkey DIR                 write signing.key / signing.pub
  make-package.py --key DIR -o PKG NAME=PATH...
"""
import hashlib, json, os, struct, sys, random

MAGIC = b"HPKG0001"


def is_probable_prime(n, k=32):
    if n < 2:
        return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0:
            return n == p
    d, r = n - 1, 0
    while d % 2 == 0:
        d //= 2
        r += 1
    for _ in range(k):
        a = random.randrange(2, n - 1)
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(r - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def gen_prime(bits, rng):
    while True:
        c = rng.getrandbits(bits) | (1 << (bits - 1)) | 1
        if is_probable_prime(c):
            return c


def genkey(dirpath, bits=1024, seed=20260906):
    # Seeded so the committed public key in the kernel and the private key here
    # can be regenerated by anyone checking this, rather than being two magic
    # blobs that have to be taken on trust.
    rng = random.Random(seed)
    half = bits // 2
    p = gen_prime(half, rng)
    q = gen_prime(half, rng)
    while q == p:
        q = gen_prime(half, rng)
    n = p * q
    if (n.bit_length() + 7) // 8 != bits // 8:
        raise SystemExit("key came out the wrong size; change the seed")
    e = 65537
    d = pow(e, -1, (p - 1) * (q - 1))
    os.makedirs(dirpath, exist_ok=True)
    with open(os.path.join(dirpath, "signing.key"), "w") as f:
        json.dump({"bits": bits, "n": n, "e": e, "d": d}, f)
    with open(os.path.join(dirpath, "signing.pub"), "w") as f:
        json.dump({"bits": bits, "n": n, "e": e}, f)
    print(f"wrote {dirpath}/signing.key and signing.pub ({bits}-bit, seed {seed})")


def pad4(b):
    return b + b"\0" * (-len(b) % 4)


def sign(digest_info, key):
    klen = key["bits"] // 8
    padlen = klen - len(digest_info) - 3
    if padlen < 8:
        raise SystemExit("key too small for a PKCS#1 v1.5 signature")
    em = b"\x00\x01" + b"\xff" * padlen + b"\x00" + digest_info
    m = int.from_bytes(em, "big")
    return pow(m, key["d"], key["n"]).to_bytes(klen, "big")


def build(keydir, out, members):
    key = json.load(open(os.path.join(keydir, "signing.key")))
    entries = b""
    for spec in members:
        name, _, path = spec.partition("=")
        if not path:
            raise SystemExit(f"expected NAME=PATH, got {spec!r}")
        data = open(path, "rb").read()
        nb = name.encode()
        entries += struct.pack("<I", len(nb)) + pad4(nb)
        entries += struct.pack("<I", len(data)) + pad4(data)

    body = MAGIC + struct.pack("<II", len(members), len(entries)) + entries
    prefix = bytes([0x30, 0x31, 0x30, 0x0d, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01,
                    0x65, 0x03, 0x04, 0x02, 0x01, 0x05, 0x00, 0x04, 0x20])
    sig = sign(prefix + hashlib.sha256(body).digest(), key)
    open(out, "wb").write(body + struct.pack("<I", len(sig)) + sig)
    print(f"wrote {out}: {len(members)} file(s), {len(body)} bytes signed, "
          f"{len(sig)}-byte signature")


def emit_pubkey_home(keydir):
    """Print the modulus as Home source, for embedding in the kernel."""
    key = json.load(open(os.path.join(keydir, "signing.pub")))
    klen = key["bits"] // 8
    nb = key["n"].to_bytes(klen, "big")
    print(f"const PANTRY_KEY_BYTES: u32 = {klen}")
    print(f"var pantry_key_n: [u8; {klen}] = undefined")
    print("fn pantry_key_init() {")
    for i, b in enumerate(nb):
        print(f"  pantry_key_n[{i}] = {b}")
    print("}")


if __name__ == "__main__":
    a = sys.argv[1:]
    if not a:
        raise SystemExit(__doc__)
    if a[0] == "--genkey":
        genkey(a[1])
    elif a[0] == "--emit-pubkey":
        emit_pubkey_home(a[1])
    elif a[0] == "--key":
        keydir = a[1]
        if a[2] != "-o":
            raise SystemExit(__doc__)
        build(keydir, a[3], a[4:])
    else:
        raise SystemExit(__doc__)
